Repository apple/coremltools, pull requests merged in 2024-04, with the labels that each got.

#2179 [ExecuTorch] Fix keys in the delegate mapping json file.
  coremltools/models/model.py
  coremltools/test/modelpackage/test_modelpackage.py
Labels: ExecuTorch

#2181 Support Indexing Bool Tensor
  coremltools/converters/mil/frontend/_utils.py
  coremltools/converters/mil/frontend/torch/ops.py
  coremltools/converters/mil/frontend/torch/test/test_torch_ops.py
  coremltools/converters/mil/frontend/torch/test/testing_utils.py
Labels: PyTorch (traced)

#2180 Make Quantizer Compatible with PyTorch 2.4
  coremltools/optimize/torch/quantization/_coreml_quantizer_utils.py
Labels: PyTorch (not traced), ExecuTorch

#2182 [ExecuTorch] Rename the Operation_Type key to Operator
  coremltools/converters/mil/frontend/torch/test/test_executorch_e2e.py
  coremltools/converters/mil/mil/program.py
Labels: ExecuTorch

#2186 [ExecuTorch] Handle 3rd Type of Const in EXIR
  coremltools/converters/mil/frontend/_utils.py
  coremltools/converters/mil/frontend/torch/exir_utils.py
  coremltools/converters/mil/frontend/torch/internal_graph.py
Labels: ExecuTorch
